#pragma once
#define CFG_TUSB_MCU OPT_MCU_NONE
#define CFG_TUSB_OS OPT_OS_NONE
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_HOST | OPT_MODE_FULL_SPEED)
#define CFG_TUD_ENABLED 0
#define CFG_TUSB_DEBUG 0
#define CFG_TUH_DEVICE_MAX 2
#define CFG_TUH_ENUMERATION_BUFSIZE 512
#define CFG_TUH_HID 4
#define CFG_TUH_HID_EPIN_BUFSIZE 64
#define CFG_TUH_HID_EPOUT_BUFSIZE 64
#define CFG_TUH_MEM_ALIGN __attribute__((aligned(4)))
#include <generated/soc.h>
#if !CONFIG_USB_ULTRA
#define TUP_USBIP_OHCI
#define TUP_USBIP_OHCI_LITEX
#define TUP_OHCI_RHPORTS 1

#endif
